### PR TITLE
Retry with require-corp if credentialless fails

### LINKED ISSUE #20: Detection of "credentialless" vs "require-corp" backwards
The current code contains the following lines in `coi-serviceworker.js`:
```
67    coepCredentialless: () => !(window.chrome || window.netscape),
```

and
```
44    coepCredentialless ? "credentialless" : "require-corp"
```

According to this logic, it says "_if the browser it NOT (Chrome or Firefox), then add 'credentialless', otherwise add 'require-corp'_"

However, the state of support is exactly backwards -- those are the only browsers that actually can use 'credentialless', and others (**such as Safari**) break when using it.

Testing with a Godot 4 app in Safari 16.5 reveals this exact behaviour -- with the current file the app is broken and we see this in the headers:
Screenshot 2023-08-01 at 01 51 36

The simple change of removing the "!" from line 67 results in the app loading (after clearing caches) and this in the headers:
Screenshot 2023-08-01 at 01 52 03

Testing the same in Chrome results in it also switching to "_require-corp_" but working nonetheless, since it supports both versions, however it appears the actual check at line 67 is not working as intended (the result when "true" is not a boolean but the actual "window.chrome" object!). Maybe this would work better?
```
coepCredentialless: () => (window.chrome !== undefined || window.netscape !== undefined),
```

Perhaps a more thorough review of the logic here should be conducted since the variable is used in other parts of the code as well.

### PR DESCRIPTION
**Pull request by tamo**
This PR would close #20, #23, and #24 as a bonus.
The idea is that, we will know the browser doesn't support COEP-credentialless if credentialless fails to establish COI.
So, we can set coi.coepDegrade to try again with require-corp.

I have tested it with the latest Firefox, Chrome, and Safari.
What I did with safari on browserstack are:
- Open index.html.
- Reload it manually.
- Type 'navigator.serviceworker.controller.postMessage({type: "deregister"})' in devtools console.
- Open it in another new tab.

Let me know if I should test it in more situations.

### CODE REVIEW

**Comment by gzuidhof** [comment]
Fantastic! Thank you :) 

I think the only situation in which this may break is in private windows - but I'm not sure about `SessionStorage`. I know that `LocalStorage` will throw in certain situations in incognito mode, I don't see why that would be the same for `SessionStorage` though.

If that does become an issue, we could use a URL query parameter instead - I'm happy to merge this how it is though

**Review by gzuidhof — APPROVED** [review]
Let me know when you are happy for me to merge this. I think this warrants a new release (version bump to `0.2.0`)

**Comment by gzuidhof** [comment]
If we wanted to be careful, we could put it in a `try catch`, but we can also do that in a later release if we do find out it's an issue in some browsers

**Comment by WasabiThumb** [comment]
Would love to have this feature in the latest NPM release. Still hanging in there with the hack I gave in #24 which [seems to work well enough](https://wasabithumb.github.io/). Assuming there are other goals that need to be met before a new version is released, if that is the case I would consider contributing towards them

**Pull request merged**
